name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: pip install .[dev]

    - name: Run Tests with pytest
      run: pytest ./tests

    - name: Type checking with mypy
      run: mypy building_energy_storage_simulation

    - name: Code style checking with ruff
      run: ruff check .