name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  installation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: pip install .[dev]

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Tests with pytest
      run: pytest ./tests

  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Type checking with mypy
      run: mypy building_energy_storage_simulation